// <auto-generated />
using System;
using LibraryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260116133933_Update_PhieuMuon_Delete_SoNgayTre")]
    partial class Update_PhieuMuon_Delete_SoNgayTre
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Models.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("PhieuMuonId")
                        .HasColumnType("int");

                    b.Property<int>("CuonSachId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrangTra")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PhieuMuonId", "CuonSachId");

                    b.HasIndex("CuonSachId");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaCuon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SachId")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ViTriKe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SachId");

                    b.ToTable("CuonSachs");
                });

            modelBuilder.Entity("LibraryManagement.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaDanhMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("MaDanhMuc")
                        .IsUnique();

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("LibraryManagement.Models.HoaDonPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhieuPhatId")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PhieuPhatId");

                    b.ToTable("HoaDonPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.NguoiMuon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LoaiDocGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNguoiMuon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.ToTable("NguoiMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhanLoai", b =>
                {
                    b.Property<int>("SachId")
                        .HasColumnType("int");

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.HasKey("SachId", "DanhMucId");

                    b.HasIndex("DanhMucId");

                    b.ToTable("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaPhieuMuon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiMuonId")
                        .HasColumnType("int");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiMuonId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PhieuMuonId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PhieuMuonId");

                    b.ToTable("PhieuPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NgonNgu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("MaSach")
                        .IsUnique();

                    b.HasIndex("TacGiaId");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("LibraryManagement.Models.TacGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaTacGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("MaTacGia")
                        .IsUnique();

                    b.ToTable("TacGias");
                });

            modelBuilder.Entity("LibraryManagement.Models.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("LibraryManagement.Models.CuonSach", "CuonSach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("CuonSachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("PhieuMuonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuonSach");

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.HasOne("LibraryManagement.Models.Sach", "Sach")
                        .WithMany("CuonSachs")
                        .HasForeignKey("SachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManagement.Models.HoaDonPhat", b =>
                {
                    b.HasOne("LibraryManagement.Models.PhieuPhat", "PhieuPhat")
                        .WithMany("HoaDonPhats")
                        .HasForeignKey("PhieuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuPhat");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhanLoai", b =>
                {
                    b.HasOne("LibraryManagement.Models.DanhMuc", "DanhMuc")
                        .WithMany("PhanLoais")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Sach", "Sach")
                        .WithMany("PhanLoais")
                        .HasForeignKey("SachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.HasOne("LibraryManagement.Models.NguoiMuon", "NguoiMuon")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("NguoiMuonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiMuon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.HasOne("LibraryManagement.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuPhats")
                        .HasForeignKey("PhieuMuonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.HasOne("LibraryManagement.Models.TacGia", "TacGia")
                        .WithMany("Sachs")
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.DanhMuc", b =>
                {
                    b.Navigation("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.NguoiMuon", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");

                    b.Navigation("PhieuPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.Navigation("HoaDonPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.Navigation("CuonSachs");

                    b.Navigation("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.TacGia", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
