// <auto-generated />
using System;
using LibraryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260126154436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Models.ChiTietPhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaCuon")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrangTra")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuMuon", "MaCuon");

                    b.HasIndex("MaCuon");

                    b.ToTable("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.Property<int>("MaCuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCuon"));

                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ViTriKe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCuon");

                    b.HasIndex("MaSach");

                    b.ToTable("CuonSachs");
                });

            modelBuilder.Entity("LibraryManagement.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("LibraryManagement.Models.HoaDonPhat", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaPhat")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaPhat");

                    b.ToTable("HoaDonPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.NguoiMuon", b =>
                {
                    b.Property<int>("MaNguoiMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiMuon"));

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LoaiDocGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiMuon");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.ToTable("NguoiMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhanLoai", b =>
                {
                    b.Property<int>("MaSach")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.HasKey("MaSach", "MaDanhMuc");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.Property<int>("MaPhieuMuon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuMuon"));

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaNguoiMuon")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuMuon");

                    b.HasIndex("MaNguoiMuon");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.Property<int>("MaPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhat"));

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaPhieuMuon")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhat");

                    b.HasIndex("MaPhieuMuon");

                    b.ToTable("PhieuPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.Property<int>("MaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSach"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaTacGia")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NgonNgu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaSach");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("MaTacGia");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("LibraryManagement.Models.TacGia", b =>
                {
                    b.Property<int>("MaTacGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTacGia"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocTich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGias");
                });

            modelBuilder.Entity("LibraryManagement.Models.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("LibraryManagement.Models.CuonSach", "CuonSach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaCuon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuonSach");

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.HasOne("LibraryManagement.Models.Sach", "Sach")
                        .WithMany("CuonSachs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManagement.Models.HoaDonPhat", b =>
                {
                    b.HasOne("LibraryManagement.Models.PhieuPhat", "PhieuPhat")
                        .WithMany("HoaDonPhats")
                        .HasForeignKey("MaPhat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuPhat");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhanLoai", b =>
                {
                    b.HasOne("LibraryManagement.Models.DanhMuc", "DanhMuc")
                        .WithMany("PhanLoais")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Sach", "Sach")
                        .WithMany("PhanLoais")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.HasOne("LibraryManagement.Models.NguoiMuon", "NguoiMuon")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaNguoiMuon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiMuon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.HasOne("LibraryManagement.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuPhats")
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.HasOne("LibraryManagement.Models.TacGia", "TacGia")
                        .WithMany("Sachs")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.DanhMuc", b =>
                {
                    b.Navigation("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.NguoiMuon", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");

                    b.Navigation("PhieuPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.Navigation("HoaDonPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.Navigation("CuonSachs");

                    b.Navigation("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.TacGia", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
