// <auto-generated />
using System;
using LibraryManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260110132739_AddEnums")]
    partial class AddEnums
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Models.ChiTietPhieuMuon", b =>
                {
                    b.Property<string>("MaPhieuMuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CuonSachMaCuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhieuMuonMaPhieuMuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TinhTrangTra")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuMuon", "MaCuon");

                    b.HasIndex("CuonSachMaCuon");

                    b.HasIndex("MaCuon");

                    b.HasIndex("PhieuMuonMaPhieuMuon");

                    b.ToTable("ChiTietPhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.Property<string>("MaCuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("SachMaSach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ViTriKe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCuon");

                    b.HasIndex("MaSach");

                    b.HasIndex("SachMaSach");

                    b.ToTable("CuonSach");
                });

            modelBuilder.Entity("LibraryManagement.Models.DanhMuc", b =>
                {
                    b.Property<string>("MaDanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("LibraryManagement.Models.HoaDonPhat", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaPhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhieuPhatMaPhat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaPhat");

                    b.HasIndex("PhieuPhatMaPhat");

                    b.ToTable("HoaDonPhat");
                });

            modelBuilder.Entity("LibraryManagement.Models.NguoiMuon", b =>
                {
                    b.Property<string>("MaNguoiMuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiDocGia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiMuon");

                    b.HasIndex("CCCD")
                        .IsUnique();

                    b.ToTable("NguoiMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhanLoai", b =>
                {
                    b.Property<string>("MaSach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaDanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DanhMucMaDanhMuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SachMaSach")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaSach", "MaDanhMuc");

                    b.HasIndex("DanhMucMaDanhMuc");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("SachMaSach");

                    b.ToTable("PhanLoai");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.Property<string>("MaPhieuMuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HanTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaNguoiMuon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiMuonMaNguoiMuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NhanVienMaNhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("SoNgayTre")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhieuMuon");

                    b.HasIndex("MaNguoiMuon");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("NguoiMuonMaNguoiMuon");

                    b.HasIndex("NhanVienMaNhanVien");

                    b.ToTable("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.Property<string>("MaPhat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhieuMuon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhieuMuonMaPhieuMuon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SoTienPhat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaPhat");

                    b.HasIndex("MaPhieuMuon");

                    b.HasIndex("PhieuMuonMaPhieuMuon");

                    b.ToTable("PhieuPhat");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.Property<string>("MaSach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("NgonNgu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaXuatBan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoTrang")
                        .HasColumnType("int");

                    b.Property<string>("TacGiaMaTacGia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaSach");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("MaTacGia");

                    b.HasIndex("TacGiaMaTacGia");

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("LibraryManagement.Models.TacGia", b =>
                {
                    b.Property<string>("MaTacGia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTacGia");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("LibraryManagement.Models.ChiTietPhieuMuon", b =>
                {
                    b.HasOne("LibraryManagement.Models.CuonSach", "CuonSach")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("CuonSachMaCuon");

                    b.HasOne("LibraryManagement.Models.CuonSach", null)
                        .WithMany()
                        .HasForeignKey("MaCuon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.PhieuMuon", null)
                        .WithMany()
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("ChiTietPhieuMuons")
                        .HasForeignKey("PhieuMuonMaPhieuMuon");

                    b.Navigation("CuonSach");

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.HasOne("LibraryManagement.Models.Sach", null)
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Sach", "Sach")
                        .WithMany("CuonSachs")
                        .HasForeignKey("SachMaSach");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManagement.Models.HoaDonPhat", b =>
                {
                    b.HasOne("LibraryManagement.Models.PhieuPhat", null)
                        .WithMany()
                        .HasForeignKey("MaPhat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.PhieuPhat", "PhieuPhat")
                        .WithMany("HoaDonPhats")
                        .HasForeignKey("PhieuPhatMaPhat");

                    b.Navigation("PhieuPhat");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhanLoai", b =>
                {
                    b.HasOne("LibraryManagement.Models.DanhMuc", "DanhMuc")
                        .WithMany("PhanLoais")
                        .HasForeignKey("DanhMucMaDanhMuc");

                    b.HasOne("LibraryManagement.Models.DanhMuc", null)
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Sach", null)
                        .WithMany()
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.Sach", "Sach")
                        .WithMany("PhanLoais")
                        .HasForeignKey("SachMaSach");

                    b.Navigation("DanhMuc");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.HasOne("LibraryManagement.Models.NguoiMuon", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiMuon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.NhanVien", null)
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.NguoiMuon", "NguoiMuon")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("NguoiMuonMaNguoiMuon");

                    b.HasOne("LibraryManagement.Models.NhanVien", "NhanVien")
                        .WithMany("PhieuMuons")
                        .HasForeignKey("NhanVienMaNhanVien");

                    b.Navigation("NguoiMuon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.HasOne("LibraryManagement.Models.PhieuMuon", null)
                        .WithMany()
                        .HasForeignKey("MaPhieuMuon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.PhieuMuon", "PhieuMuon")
                        .WithMany("PhieuPhats")
                        .HasForeignKey("PhieuMuonMaPhieuMuon");

                    b.Navigation("PhieuMuon");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.HasOne("LibraryManagement.Models.TacGia", null)
                        .WithMany()
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibraryManagement.Models.TacGia", "TacGia")
                        .WithMany("Sachs")
                        .HasForeignKey("TacGiaMaTacGia");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("LibraryManagement.Models.CuonSach", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.DanhMuc", b =>
                {
                    b.Navigation("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.NguoiMuon", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.NhanVien", b =>
                {
                    b.Navigation("PhieuMuons");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuMuon", b =>
                {
                    b.Navigation("ChiTietPhieuMuons");

                    b.Navigation("PhieuPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.PhieuPhat", b =>
                {
                    b.Navigation("HoaDonPhats");
                });

            modelBuilder.Entity("LibraryManagement.Models.Sach", b =>
                {
                    b.Navigation("CuonSachs");

                    b.Navigation("PhanLoais");
                });

            modelBuilder.Entity("LibraryManagement.Models.TacGia", b =>
                {
                    b.Navigation("Sachs");
                });
#pragma warning restore 612, 618
        }
    }
}
